# Generated by Django 3.1.7 on 2022-06-05 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20220605_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 12, 6, 54, 568169), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='state',
            field=models.CharField(default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='content',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 12, 6, 54, 567299), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='content',
            name='state',
            field=models.CharField(default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 12, 6, 54, 567711), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='state',
            field=models.CharField(default='AC', max_length=2),
        ),
    ]
