# Generated by Django 3.1.7 on 2022-06-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='topic',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
