# Generated by Django 3.1.7 on 2022-06-05 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 12, 6, 54, 548232), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='card',
            name='state',
            field=models.CharField(default='AC', max_length=2),
        ),
    ]
